/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToPlaylistModal: typeof import('./components/AddToPlaylistModal.vue')['default']
    AlbumView: typeof import('./views/AlbumView.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ClientConfigView: typeof import('./views/ClientConfigView.vue')['default']
    CountryCard: typeof import('./components/CountryCard.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    EqualizerControl: typeof import('./components/EqualizerControl.vue')['default']
    EqualizerView: typeof import('./views/EqualizerView.vue')['default']
    FavouritesList: typeof import('./components/FavouritesList.vue')['default']
    FilePlaylistView: typeof import('./views/FilePlaylistView.vue')['default']
    LibraryView: typeof import('./views/LibraryView.vue')['default']
    LocalPlaylistView: typeof import('./views/LocalPlaylistView.vue')['default']
    MediaCard: typeof import('./components/MediaCard.vue')['default']
    MediaCardGrid: typeof import('./components/MediaCardGrid.vue')['default']
    MediaTrackList: typeof import('./components/MediaTrackList.vue')['default']
    NowPlayingView: typeof import('./views/NowPlayingView.vue')['default']
    PlayerFooter: typeof import('./components/PlayerFooter.vue')['default']
    PlaylistView: typeof import('./views/PlaylistView.vue')['default']
    PodcastView: typeof import('./views/PodcastView.vue')['default']
    PodverseView: typeof import('./views/PodverseView.vue')['default']
    PreviousPageButton: typeof import('./components/PreviousPageButton.vue')['default']
    RadioView: typeof import('./views/RadioView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./views/SearchView.vue')['default']
    ShowView: typeof import('./views/ShowView.vue')['default']
    TuneInView: typeof import('./views/TuneInView.vue')['default']
  }
}
