/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumView: typeof import('./views/AlbumView.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ClientConfigView: typeof import('./views/ClientConfigView.vue')['default']
    CountryCard: typeof import('./components/CountryCard.vue')['default']
    FavouritesList: typeof import('./components/FavouritesList.vue')['default']
    LibrespotView: typeof import('./views/LibrespotView.vue')['default']
    MediaCard: typeof import('./components/MediaCard.vue')['default']
    MediaCardGrid: typeof import('./components/MediaCardGrid.vue')['default']
    MpdView: typeof import('./views/MpdView.vue')['default']
    NowPlayingView: typeof import('./views/NowPlayingView.vue')['default']
    PlayerFooter: typeof import('./components/PlayerFooter.vue')['default']
    PlaylistView: typeof import('./views/PlaylistView.vue')['default']
    PodcastView: typeof import('./views/PodcastView.vue')['default']
    PodverseView: typeof import('./views/PodverseView.vue')['default']
    RadioView: typeof import('./views/RadioView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./views/SearchView.vue')['default']
    ShowView: typeof import('./views/ShowView.vue')['default']
    SnapcastView: typeof import('./views/SnapcastView.vue')['default']
    SpotifyView: typeof import('./views/SpotifyView.vue')['default']
    TuneInView: typeof import('./views/TuneInView.vue')['default']
  }
}
