// File: CompactStringCipher.cs
namespace Viox.Core.Utilities;

using System;
using System.Security.Cryptography;
using System.Text;

/// <summary>
/// Provides compact, reversible string encryption using AES-CTR and custom Base62 encoding.
/// </summary>
public class CompactStringCipher
{
    private const string Base62Chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private readonly byte[] _key;

    public CompactStringCipher()
    {
        string base64Key = "ajhYL3FQMnZLOUw0bU42ejdXMXRSN3lVM29QNXNBOGQ=";
        _key = Convert.FromBase64String(base64Key);

        if (_key.Length != 32)
        {
            throw new ArgumentException("Key must be 256 bits (32 bytes).");
        }
    }

    /// <summary>
    /// Encrypts an input string into a short, URL-safe Base62 cipher string.
    /// </summary>
    /// <param name="plainText">The string to encrypt.</param>
    /// <returns>A compact, reversible string representation.</returns>
    public string Encrypt(string plainText)
    {
        ArgumentNullException.ThrowIfNull(plainText);

        if (string.IsNullOrEmpty(plainText))
        {
            return string.Empty;
        }

        Span<byte> iv = stackalloc byte[16];
        RandomNumberGenerator.Fill(iv);

        byte[] plainBytes = Encoding.UTF8.GetBytes(plainText);
        byte[] cipherBytes = TransformAesCtr(plainBytes, _key, iv);

        // Combine 8-byte reduced IV prefix + cipher bytes for compactness
        byte[] payload = new byte[8 + cipherBytes.Length];
        iv[..8].CopyTo(payload.AsSpan(0, 8));
        cipherBytes.CopyTo(payload.AsSpan(8));

        return EncodeBase62(payload);
    }

    /// <summary>
    /// Decrypts a compact Base62 cipher string back to the original plaintext.
    /// </summary>
    /// <param name="cipherText">The compact Base62 string generated by <see cref="Encrypt"/>.</param>
    /// <returns>The original decrypted plaintext string.</returns>
    public string Decrypt(string cipherText)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(cipherText);

        byte[] payload = DecodeBase62(cipherText);
        if (payload.Length < 9)
        {
            throw new ArgumentException("Invalid compact cipher string length.", nameof(cipherText));
        }

        Span<byte> iv = stackalloc byte[16];
        iv.Clear();
        payload.AsSpan(0, 8).CopyTo(iv);

        ReadOnlySpan<byte> cipherBytes = payload.AsSpan(8);
        byte[] plainBytes = TransformAesCtr(cipherBytes.ToArray(), _key, iv);

        return Encoding.UTF8.GetString(plainBytes);
    }

    private static byte[] TransformAesCtr(byte[] input, byte[] key, ReadOnlySpan<byte> iv)
    {
        using var aes = Aes.Create();
        aes.Key = key;
        aes.Mode = CipherMode.ECB;
        aes.Padding = PaddingMode.None;

        using var encryptor = aes.CreateEncryptor();
        byte[] result = new byte[input.Length];

        Span<byte> counter = stackalloc byte[16];
        iv.CopyTo(counter);

        Span<byte> counterOutput = stackalloc byte[16];

        for (int i = 0; i < input.Length; i += 16)
        {
            encryptor.TransformBlock(counter.ToArray(), 0, 16, counterOutput.ToArray(), 0);

            // Increment counter
            for (int j = 15; j >= 0; j--)
            {
                if (++counter[j] != 0)
                {
                    break;
                }
            }

            int blockSize = Math.Min(16, input.Length - i);
            for (int b = 0; b < blockSize; b++)
            {
                result[i + b] = (byte)(input[i + b] ^ counterOutput[b]);
            }
        }

        return result;
    }

    private static string EncodeBase62(ReadOnlySpan<byte> input)
    {
        var sb = new StringBuilder();
        var value = new System.Numerics.BigInteger(input, isUnsigned: true, isBigEndian: true);

        while (value > 0)
        {
            value = System.Numerics.BigInteger.DivRem(value, 62, out var remainder);
            sb.Insert(0, Base62Chars[(int)remainder]);
        }

        return sb.Length == 0 ? "0" : sb.ToString();
    }

    private static byte[] DecodeBase62(string input)
    {
        var value = System.Numerics.BigInteger.Zero;

        foreach (char c in input)
        {
            int index = Base62Chars.IndexOf(c);
            if (index == -1)
            {
                throw new FormatException($"Invalid Base62 character '{c}'.");
            }

            value = (value * 62) + index;
        }

        return value.ToByteArray(isUnsigned: true, isBigEndian: true);
    }
}
