# Default ALSA entry point for applications targeting 'default'
pcm.!default {
    type plug
    slave.pcm "hardware"
}

# Direct Hardware PCM Device (explicitly targeted by snapclient)
pcm.hardware {
    type plug
    slave {
        pcm {
            type hw
            card {
                @func getenv
                vars [ AUDIO_CARD ALSA_CARD ]
                default 0 # Falls back to card index 0 if AUDIO_CARD/ALSA_CARD is unset
            }
            device 0
        }
    }
}

# Control device fallback (for amixer/alsamixer)
ctl.!default {
    type hw
    card {
        @func getenv
        vars [ AUDIO_CARD ALSA_CARD ]
        default 0
    }
}
