defaults.pcm.rate_converter "speexrate_best"
#defaults.pcm.rate_converter "soxr-vhq"

# Default ALSA device entrypoint
pcm.!default {
    type plug
    slave.pcm "plugequal"
}

# ALSA Equalizer control interface
ctl.equal {
    type equal
    controls "/data/alsaequal.bin"
}

# The Equalizer node surrounded by plug interfaces for format conversion
pcm.plugequal {
    type equal
    slave.pcm "plugdmix"
    controls "/data/alsaequal.bin"
}

pcm.plugdmix {
    type plug
    slave.pcm "dmixer"
}

# Mixer output configuration
pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_key_add_uid true
    slave {
        pcm {
            type hw
            card {
                @func getenv
                vars [ AUDIO_CARD ALSA_CARD ]
                default "AUDIO"
            }
            device 0
        }
        format S32_LE
        rate 44100
        channels 2
        period_size 1024
        buffer_size 8192
    }
    bindings {
        0 0
        1 1
    }
}

ctl.!default {
    type hw
    card {
        @func getenv
        vars [ AUDIO_CARD ALSA_CARD ]
        default "AUDIO"
    }
}
