# Lighter rate converter to minimize processing latency
defaults.pcm.rate_converter "speexrate_medium"

# 1. Default ALSA entry point (for audio sources like MPD / Golibrespot)
pcm.!default {
    type plug
    slave.pcm "plugequal"
}

# 2. ALSA Equalizer control interface (for alsamixer -D equal)
ctl.equal {
    type equal
    controls "/data/alsaequal.bin"
}

# 3. Plug wrapper for ALSA Equalizer
pcm.plugequal {
    type plug
    slave.pcm "equal"
}

# 4. Raw LADSPA Equalizer PCM device
pcm.equal {
    type equal
    slave.pcm "snap_fifo"
    controls "/data/alsaequal.bin"
}

# 5. File PCM plugin writing raw PCM directly to Snapserver's pipe
pcm.snap_fifo {
    type plug
    slave {
        pcm {
            type file
            file "/tmp/snapfifo"
            format "raw"
            slave.pcm "null"
        }
        format S16_LE
        rate 44100
        channels 2
    }
}

# 6. Direct Hardware PCM Device (Targeted specifically by snapclient)
pcm.hardware {
    type plug
    slave {
        pcm {
            type hw
            card {
                @func getenv
                vars [ AUDIO_CARD ALSA_CARD ]
                default 0 # Fall back to card 0 instead of string "AUDIO"
            }
            device 0
        }
    }
}

# 7. Hardware control interface
ctl.!default {
    type hw
    card {
        @func getenv
        vars [ AUDIO_CARD ALSA_CARD ]
        default 0
    }
}
