[server]
user = root
group = root

[http]
enabled = true
bind_to_address = 127.0.0.1
port = 1780
ssl_enabled = false

[tcp]
port = 1705
enabled = true
bind_to_address = 0.0.0.0

[stream]
source = pipe:///audio/output?name=VioxDotNet&mode=read&sampleformat=44100:16:2
bind_to_address = 0.0.0.0
port = 1704
sampleformat = 44100:16:2
codec = flac
chunk_ms = 26
buffer = 1000
send_to_muted = false

[streaming_client]

[logging]
sink =stdout
